# Generated by Django 3.2.3 on 2021-05-20 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_all_activity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='all_activity',
            name='full',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='answers',
            name='choise',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='Currect_ans',
            field=models.CharField(max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='question',
            field=models.CharField(max_length=300, null=True),
        ),
    ]
