# Generated by Django 3.2.3 on 2021-05-20 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_question_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='name',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
