# Generated by Django 3.2.3 on 2021-05-21 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_answers_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='answers',
            name='name',
        ),
        migrations.AlterField(
            model_name='all_activity',
            name='full',
            field=models.CharField(max_length=500),
        ),
    ]
