# Generated by Django 3.2.3 on 2021-05-28 05:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20210521_1237'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Currect_ans',
        ),
    ]
