# Generated by Django 3.2.3 on 2021-05-28 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_remove_question_currect_ans'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Currect_ans',
            field=models.CharField(max_length=80, null=True),
        ),
    ]
