# Generated by Django 3.2.3 on 2021-05-28 06:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0009_question_currect_ans'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Answers',
        ),
        migrations.RemoveField(
            model_name='all_activity',
            name='visible',
        ),
    ]
